// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_C0aVWE7bo-K08OfhpWQ8MDOgMtjtBro',
    appId: '1:846731048901:web:0b4aeaa558346ba05b7dac',
    messagingSenderId: '846731048901',
    projectId: 'soundcircle-2afcd',
    authDomain: 'soundcircle-2afcd.firebaseapp.com',
    storageBucket: 'soundcircle-2afcd.appspot.com',
    measurementId: 'G-4TRWSMQCBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_h3uFSTkNCyEVJpGtGaSSUk18O_yeUEI',
    appId: '1:846731048901:android:800b8af63b11a4335b7dac',
    messagingSenderId: '846731048901',
    projectId: 'soundcircle-2afcd',
    storageBucket: 'soundcircle-2afcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3xgShJRp_qAIkJ7gj9ZPEMdYkpHX-oA',
    appId: '1:846731048901:ios:8f43a46d780b1c325b7dac',
    messagingSenderId: '846731048901',
    projectId: 'soundcircle-2afcd',
    storageBucket: 'soundcircle-2afcd.appspot.com',
    iosBundleId: 'com.example.soundcircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn3xgShJRp_qAIkJ7gj9ZPEMdYkpHX-oA',
    appId: '1:846731048901:ios:8f43a46d780b1c325b7dac',
    messagingSenderId: '846731048901',
    projectId: 'soundcircle-2afcd',
    storageBucket: 'soundcircle-2afcd.appspot.com',
    iosBundleId: 'com.example.soundcircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_C0aVWE7bo-K08OfhpWQ8MDOgMtjtBro',
    appId: '1:846731048901:web:f2f440e9be7a6d855b7dac',
    messagingSenderId: '846731048901',
    projectId: 'soundcircle-2afcd',
    authDomain: 'soundcircle-2afcd.firebaseapp.com',
    storageBucket: 'soundcircle-2afcd.appspot.com',
    measurementId: 'G-0H0KGBC9RJ',
  );

}